/**
 * Auto-generated execution implementation for Bdev ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include <chimaera/bdev/bdev_runtime.h>
#include <chimaera/bdev/autogen/bdev_methods.h>
#include <chimaera/chimaera.h>

namespace chimaera::bdev_extended {

using namespace chimaera::bdev_extended;

//==============================================================================
// Runtime Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      // Destroy not implemented yet
      break;
    }
    case Method::kAllocate: {
      Allocate(task_ptr.Cast<AllocateTask>(), rctx);
      break;
    }
    case Method::kFree: {
      Free(task_ptr.Cast<FreeTask>(), rctx);
      break;
    }
    case Method::kWrite: {
      Write(task_ptr.Cast<WriteTask>(), rctx);
      break;
    }
    case Method::kRead: {
      Read(task_ptr.Cast<ReadTask>(), rctx);
      break;
    }
    case Method::kGetStats: {
      GetStats(task_ptr.Cast<StatTask>(), rctx);
      break;
    }
    case Method::kRegisterTarget: {
      RegisterTarget(task_ptr.Cast<RegisterTargetTask>(), rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      UnregisterTarget(task_ptr.Cast<UnregisterTargetTask>(), rctx);
      break;
    }
    case Method::kListTargets: {
      ListTargets(task_ptr.Cast<ListTargetsTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      // MonitorDestroy not implemented yet
      break;
    }
    case Method::kAllocate: {
      MonitorAllocate(mode, task_ptr.Cast<AllocateTask>(), rctx);
      break;
    }
    case Method::kFree: {
      MonitorFree(mode, task_ptr.Cast<FreeTask>(), rctx);
      break;
    }
    case Method::kWrite: {
      MonitorWrite(mode, task_ptr.Cast<WriteTask>(), rctx);
      break;
    }
    case Method::kRead: {
      MonitorRead(mode, task_ptr.Cast<ReadTask>(), rctx);
      break;
    }
    case Method::kGetStats: {
      MonitorGetStats(mode, task_ptr.Cast<StatTask>(), rctx);
      break;
    }
    case Method::kRegisterTarget: {
      MonitorRegisterTarget(mode, task_ptr.Cast<RegisterTargetTask>(), rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      MonitorUnregisterTarget(mode, task_ptr.Cast<UnregisterTargetTask>(), rctx);
      break;
    }
    case Method::kListTargets: {
      MonitorListTargets(mode, task_ptr.Cast<ListTargetsTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      // DestroyTask not implemented yet - use generic delete
      ipc_manager->DelTask(task_ptr);
      break;
    }
    case Method::kAllocate: {
      ipc_manager->DelTask(task_ptr.Cast<AllocateTask>());
      break;
    }
    case Method::kFree: {
      ipc_manager->DelTask(task_ptr.Cast<FreeTask>());
      break;
    }
    case Method::kWrite: {
      ipc_manager->DelTask(task_ptr.Cast<WriteTask>());
      break;
    }
    case Method::kRead: {
      ipc_manager->DelTask(task_ptr.Cast<ReadTask>());
      break;
    }
    case Method::kGetStats: {
      ipc_manager->DelTask(task_ptr.Cast<StatTask>());
      break;
    }
    case Method::kRegisterTarget: {
      ipc_manager->DelTask(task_ptr.Cast<RegisterTargetTask>());
      break;
    }
    case Method::kUnregisterTarget: {
      ipc_manager->DelTask(task_ptr.Cast<UnregisterTargetTask>());
      break;
    }
    case Method::kListTargets: {
      ipc_manager->DelTask(task_ptr.Cast<ListTargetsTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

chi::u64 Runtime::GetWorkRemaining() const {
  // Return approximate work remaining (simple implementation)
  // In a real implementation, this would sum tasks across all queues
  return 0; // For now, always return 0 work remaining
}

// SaveIn, LoadIn, SaveOut, LoadOut, and NewCopy methods follow similar patterns
// These are typically auto-generated for serialization support

void Runtime::SaveIn(chi::u32 method, chi::TaskSaveInArchive& archive,
                     hipc::FullPtr<chi::Task> task_ptr) {
  // Serialization input not implemented for this module yet
  (void)method;
  (void)archive;
  (void)task_ptr;
}

void Runtime::LoadIn(chi::u32 method, chi::TaskLoadInArchive& archive,
                     hipc::FullPtr<chi::Task> task_ptr) {
  // Deserialization input not implemented for this module yet  
  (void)method;
  (void)archive;
  (void)task_ptr;
}

void Runtime::SaveOut(chi::u32 method, chi::TaskSaveOutArchive& archive,
                      hipc::FullPtr<chi::Task> task_ptr) {
  // Serialization output not implemented for this module yet
  (void)method;
  (void)archive;
  (void)task_ptr;
}

void Runtime::LoadOut(chi::u32 method, chi::TaskLoadOutArchive& archive,
                      hipc::FullPtr<chi::Task> task_ptr) {
  // Deserialization output not implemented for this module yet
  (void)method;
  (void)archive;
  (void)task_ptr;
}

void Runtime::NewCopy(chi::u32 method, const hipc::FullPtr<chi::Task> &orig_task,
                      hipc::FullPtr<chi::Task> &dup_task, bool deep) {
  // Task copying not implemented for this module yet
  (void)method;
  (void)orig_task;
  (void)deep;
  dup_task = hipc::FullPtr<chi::Task>();
}

// Legacy autogen API implementations
void Runtime::SaveIn(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  (void)method;
  (void)task_ptr;
}

void Runtime::LoadIn(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  (void)method;
  (void)task_ptr;
}

void Runtime::SaveOut(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  (void)method;
  (void)task_ptr;
}

void Runtime::LoadOut(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  (void)method;
  (void)task_ptr;
}

hipc::FullPtr<chi::Task> Runtime::NewCopy(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  (void)method;
  (void)task_ptr;
  return hipc::FullPtr<chi::Task>();
}

} // namespace chimaera::bdev_extended