/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/core/core_runtime.h"
#include "chimaera/core/autogen/core_methods.h"
#include <chimaera/chimaera.h>

namespace wrp_cte::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      Destroy(task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kRegisterTarget: {
      RegisterTarget(task_ptr.Cast<RegisterTargetTask>(), rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      UnregisterTarget(task_ptr.Cast<UnregisterTargetTask>(), rctx);
      break;
    }
    case Method::kListTargets: {
      ListTargets(task_ptr.Cast<ListTargetsTask>(), rctx);
      break;
    }
    case Method::kStatTargets: {
      StatTargets(task_ptr.Cast<StatTargetsTask>(), rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      GetOrCreateTag(task_ptr.Cast<core::GetOrCreateTagTask<core::CreateParams>>(), rctx);
      break;
    }
    case Method::kPutBlob: {
      PutBlob(task_ptr.Cast<PutBlobTask>(), rctx);
      break;
    }
    case Method::kGetBlob: {
      GetBlob(task_ptr.Cast<GetBlobTask>(), rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      ReorganizeBlob(task_ptr.Cast<ReorganizeBlobTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      MonitorDestroy(mode, task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kRegisterTarget: {
      MonitorRegisterTarget(mode, task_ptr.Cast<RegisterTargetTask>(), rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      MonitorUnregisterTarget(mode, task_ptr.Cast<UnregisterTargetTask>(), rctx);
      break;
    }
    case Method::kListTargets: {
      MonitorListTargets(mode, task_ptr.Cast<ListTargetsTask>(), rctx);
      break;
    }
    case Method::kStatTargets: {
      MonitorStatTargets(mode, task_ptr.Cast<StatTargetsTask>(), rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      MonitorGetOrCreateTag(mode, task_ptr.Cast<core::GetOrCreateTagTask<core::CreateParams>>(), rctx);
      break;
    }
    case Method::kPutBlob: {
      MonitorPutBlob(mode, task_ptr.Cast<PutBlobTask>(), rctx);
      break;
    }
    case Method::kGetBlob: {
      MonitorGetBlob(mode, task_ptr.Cast<GetBlobTask>(), rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      MonitorReorganizeBlob(mode, task_ptr.Cast<ReorganizeBlobTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyTask>());
      break;
    }
    case Method::kRegisterTarget: {
      ipc_manager->DelTask(task_ptr.Cast<RegisterTargetTask>());
      break;
    }
    case Method::kUnregisterTarget: {
      ipc_manager->DelTask(task_ptr.Cast<UnregisterTargetTask>());
      break;
    }
    case Method::kListTargets: {
      ipc_manager->DelTask(task_ptr.Cast<ListTargetsTask>());
      break;
    }
    case Method::kStatTargets: {
      ipc_manager->DelTask(task_ptr.Cast<StatTargetsTask>());
      break;
    }
    case Method::kGetOrCreateTag: {
      ipc_manager->DelTask(task_ptr.Cast<core::GetOrCreateTagTask<core::CreateParams>>());
      break;
    }
    case Method::kPutBlob: {
      ipc_manager->DelTask(task_ptr.Cast<PutBlobTask>());
      break;
    }
    case Method::kGetBlob: {
      ipc_manager->DelTask(task_ptr.Cast<GetBlobTask>());
      break;
    }
    case Method::kReorganizeBlob: {
      ipc_manager->DelTask(task_ptr.Cast<ReorganizeBlobTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveIn(chi::u32 method, chi::TaskSaveInArchive& archive, 
                      hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.Cast<RegisterTargetTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.Cast<UnregisterTargetTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.Cast<ListTargetsTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.Cast<StatTargetsTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.Cast<PutBlobTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.Cast<GetBlobTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.Cast<ReorganizeBlobTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadIn(chi::u32 method, chi::TaskLoadInArchive& archive, 
                      hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.Cast<RegisterTargetTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.Cast<UnregisterTargetTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.Cast<ListTargetsTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.Cast<StatTargetsTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.Cast<PutBlobTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.Cast<GetBlobTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.Cast<ReorganizeBlobTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::SaveOut(chi::u32 method, chi::TaskSaveOutArchive& archive, 
                       hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.Cast<RegisterTargetTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.Cast<UnregisterTargetTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.Cast<ListTargetsTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.Cast<StatTargetsTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.Cast<PutBlobTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.Cast<GetBlobTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.Cast<ReorganizeBlobTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadOut(chi::u32 method, chi::TaskLoadOutArchive& archive, 
                       hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.Cast<RegisterTargetTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.Cast<UnregisterTargetTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.Cast<ListTargetsTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.Cast<StatTargetsTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.Cast<PutBlobTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.Cast<GetBlobTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.Cast<ReorganizeBlobTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, const hipc::FullPtr<chi::Task>& orig_task,
                       hipc::FullPtr<chi::Task>& dup_task, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CreateTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CreateTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<DestroyTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRegisterTarget: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<RegisterTargetTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<RegisterTargetTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kUnregisterTarget: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<UnregisterTargetTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<UnregisterTargetTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kListTargets: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ListTargetsTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<ListTargetsTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kStatTargets: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<StatTargetsTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<StatTargetsTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreateTag: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<core::GetOrCreateTagTask<core::CreateParams>>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kPutBlob: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<PutBlobTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<PutBlobTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlob: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<GetBlobTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<GetBlobTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kReorganizeBlob: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ReorganizeBlobTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<ReorganizeBlobTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto typed_task = ipc_manager->NewTask<chi::Task>();
      if (!typed_task.IsNull()) {
        typed_task->shm_strong_copy_main(*orig_task);
        dup_task = typed_task;  // Already chi::Task type
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

} // namespace wrp_cte::core
