/**
 * Auto-generated execution implementation for CTE Core ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include <chimaera/core/core_runtime.h>
#include <chimaera/core/autogen/core_methods.h>
#include <chimaera/chimaera.h>

namespace wrp_cte::core {

//==============================================================================
// Runtime Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      // Destroy not implemented yet
      break;
    }
    case Method::kRegisterTarget: {
      RegisterTarget(task_ptr.Cast<RegisterTargetTask>(), rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      UnregisterTarget(task_ptr.Cast<UnregisterTargetTask>(), rctx);
      break;
    }
    case Method::kListTargets: {
      ListTargets(task_ptr.Cast<ListTargetsTask>(), rctx);
      break;
    }
    case Method::kStatTargets: {
      StatTargets(task_ptr.Cast<StatTargetsTask>(), rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      GetOrCreateTag(task_ptr.Cast<GetOrCreateTagTask>(), rctx);
      break;
    }
    case Method::kPutBlob: {
      PutBlob(task_ptr.Cast<PutBlobTask>(), rctx);
      break;
    }
    case Method::kGetBlob: {
      GetBlob(task_ptr.Cast<GetBlobTask>(), rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      ReorganizeBlob(task_ptr.Cast<ReorganizeBlobTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      // MonitorDestroy not implemented yet
      break;
    }
    case Method::kRegisterTarget: {
      MonitorRegisterTarget(mode, task_ptr.Cast<RegisterTargetTask>(), rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      MonitorUnregisterTarget(mode, task_ptr.Cast<UnregisterTargetTask>(), rctx);
      break;
    }
    case Method::kListTargets: {
      MonitorListTargets(mode, task_ptr.Cast<ListTargetsTask>(), rctx);
      break;
    }
    case Method::kStatTargets: {
      MonitorStatTargets(mode, task_ptr.Cast<StatTargetsTask>(), rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      MonitorGetOrCreateTag(mode, task_ptr.Cast<GetOrCreateTagTask>(), rctx);
      break;
    }
    case Method::kPutBlob: {
      MonitorPutBlob(mode, task_ptr.Cast<PutBlobTask>(), rctx);
      break;
    }
    case Method::kGetBlob: {
      MonitorGetBlob(mode, task_ptr.Cast<GetBlobTask>(), rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      MonitorReorganizeBlob(mode, task_ptr.Cast<ReorganizeBlobTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      // DestroyTask not implemented yet - use generic delete
      ipc_manager->DelTask(task_ptr);
      break;
    }
    case Method::kRegisterTarget: {
      ipc_manager->DelTask(task_ptr.Cast<RegisterTargetTask>());
      break;
    }
    case Method::kUnregisterTarget: {
      ipc_manager->DelTask(task_ptr.Cast<UnregisterTargetTask>());
      break;
    }
    case Method::kListTargets: {
      ipc_manager->DelTask(task_ptr.Cast<ListTargetsTask>());
      break;
    }
    case Method::kStatTargets: {
      ipc_manager->DelTask(task_ptr.Cast<StatTargetsTask>());
      break;
    }
    case Method::kGetOrCreateTag: {
      ipc_manager->DelTask(task_ptr.Cast<GetOrCreateTagTask>());
      break;
    }
    case Method::kPutBlob: {
      ipc_manager->DelTask(task_ptr.Cast<PutBlobTask>());
      break;
    }
    case Method::kGetBlob: {
      ipc_manager->DelTask(task_ptr.Cast<GetBlobTask>());
      break;
    }
    case Method::kReorganizeBlob: {
      ipc_manager->DelTask(task_ptr.Cast<ReorganizeBlobTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

// SaveIn, LoadIn, SaveOut, LoadOut, and NewCopy methods would follow similar patterns
// These are typically auto-generated for serialization support

void Runtime::SaveIn(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Serialization input not implemented for this module yet
  (void)method;
  (void)task_ptr;
}

void Runtime::LoadIn(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Deserialization input not implemented for this module yet  
  (void)method;
  (void)task_ptr;
}

void Runtime::SaveOut(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Serialization output not implemented for this module yet
  (void)method;
  (void)task_ptr;
}

void Runtime::LoadOut(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Deserialization output not implemented for this module yet
  (void)method;
  (void)task_ptr;
}

hipc::FullPtr<chi::Task> Runtime::NewCopy(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Task copying not implemented for this module yet
  (void)method;
  (void)task_ptr;
  return hipc::FullPtr<chi::Task>();
}

} // namespace wrp_cte::core